### ISSUE TITLE
Clarification on project

### ISSUE THREAD

**Issue by djsegal** [pmargreff/juliavm#2]
I sent this project along to a friend and he responded with the following email.

Does any of this seem to resonate with you?

------------

from the email:

> I'm more interested in _package_ version switching than Julia version management.
>
> Check out how npm can install packages _locally_: https://docs.npmjs.com/getting-started/installing-npm-packages-locally
>
> This makes it so that every project you work on can have it's own versions of all of its dependent packages.  They are stored right inside the directory for that project.
>
> In fact, when you get a project (like from GitHub) you just go into the repository and type "npm install"... that will read the package.json for the project and install all the dependencies for that project _inside_ the current directory.  It's incredibly simple and makes it really easy to work across multiple projects with different package requirements.
>
> In Python people usually use "virtual environments" like "virtualenv" or "conda".  This allows you to basically switch between multiple "globally" installed sets of packages when you're working on different projects.  It "works"... but is not as seamless and uncomplicated as npm local installs.

**Comment by pmargreff** [comment]
@djsegal hey there. 

Thank you for share the project. When I started the project the main goal to solve was switching between Julia versions to be able to write different projects without broke projects coded in another version. It occurs sometimes in new releases happens since Julia isn't so stable yet. 

You can suggest or search something like your friend says in [discourse](https://discourse.julialang.org/).
